/* ===========================================================================
   Norte — seed the database from the repo
   ---------------------------------------------------------------------------
   data/market/*.json stays the source of truth. This turns it into SQL.

       node db/seed.mjs              write db/seed.sql
       node db/seed.mjs | psql ...   or pipe it straight in

   Every row goes in whole, as jsonb, with no field-by-field mapping. That is
   the point of the schema: nothing here has to know what a column means, so a
   new column added by the market-data skill needs no change to this file.

   Insert order follows the foreign keys. If an issuer_id on a card does not
   exist in issuers, the load fails loudly here rather than showing up months
   later as a card with no bank name.
   =========================================================================== */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const M = (n) => JSON.parse(fs.readFileSync(path.join(ROOT, 'data/market', n + '.json'), 'utf8'));

/** [table, json file, id field] in dependency order. */
const TABLES = [
  ['issuers',            'issuers',            'issuer_id'],
  ['cards',              'cards',              'card_id'],
  ['card_rewards',       'card_rewards',       'reward_id'],
  ['accounts',           'accounts',           'account_id'],
  ['yield_tiers',        'yield_tiers',        'tier_id'],
  ['term_tiers',         'term_tiers',         'term_id'],
  ['conditional_boosts', 'conditional_boosts', 'boost_id'],
  ['categories',         'categories',         'category_key'],
  ['fx_rates',           'fx_rates',           'pair'],
  ['reference_rates',    'reference_rates',    'index'],
];

/* Dollar quoting: JSON can contain every kind of quote and backslash, but it
   cannot contain this tag, so no escaping pass is needed and none can be got
   wrong. */
const TAG = '$norte$';
const lit = (obj) => TAG + JSON.stringify(obj) + TAG;

const out = [];
const say = (s) => out.push(s);

say('-- GENERATED by db/seed.mjs from data/market/*.json. Do not edit.');
say(`-- ${new Date().toISOString().slice(0, 10)}`);
say('');
say('begin;');
say('');

// Truncate in reverse dependency order so the FKs never complain.
say('-- Replace wholesale: the repo is the source of truth, so a partial');
say('-- update is never what is wanted here.');
for (const [table] of [...TABLES].reverse()) say(`delete from ${table};`);
say('');

let total = 0;
for (const [table, file, idField] of TABLES) {
  const rows = M(file);
  const seen = new Set();
  say(`-- ${table}: ${rows.length} rows`);
  for (const row of rows) {
    const id = row[idField];
    if (id == null || id === '') throw new Error(`${file}: a row has no ${idField}`);
    if (seen.has(id)) throw new Error(`${file}: duplicate ${idField} ${id}`);
    seen.add(id);
    say(`insert into ${table} (raw) values (${lit(row)}::jsonb);`);
  }
  say('');
  total += rows.length;
}

say('commit;');
say('');
say(`-- ${total} rows across ${TABLES.length} tables`);

const sql = out.join('\n') + '\n';
if (process.argv.includes('--stdout')) {
  process.stdout.write(sql);
} else {
  fs.writeFileSync(path.join(ROOT, 'db/seed.sql'), sql);
  console.error(`db/seed.sql: ${total} rows across ${TABLES.length} tables`);
}
